name: Build and Deploy PROD

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API_PROD }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL_PROD }}
        run: npm run build

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: dist/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: server-artifact

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '*'
          target: ${{ vars.OUTPUT_DIR_PROD }}

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart ${{ vars.SERVICE_NAME }}
