name: Test build on Pull Request

on:
  pull_request:
    types:
      - opened
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test & Build
        run: npm run build
