name: Test build on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test & Build
        env:
          VITE_HOST_API: ${{ vars.VITE_HOST_API }}
          VITE_LOG_LEVEL: ${{ vars.VITE_LOG_LEVEL }}
        run: npm run build
